packages:
  - "configuration/*"
  - "packages/*"
  - "cucumber/*"
  - "libraries/*"
  - "documentation/*"
  - "**/dist"
  # - "playwright/*"

  # - "selenium/*"
  # - "cucumber/*"
  # - "libraries/*"
