/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cucumberRunnerBar: [
    {
      type: "category",
      label: "Autometa",
      items: [{ type: "autogenerated", dirName: "cucumber/test_runner" }],
      // items: ["cucumber/test_runner/intro"],
    },
  ],
  cucumberRunnerBarLegacy: [
    {
      type: "category",
      label: "Test Runner (Legacy)",
      items: [{ type: "autogenerated", dirName: "cucumber/test_runner_legacy" }],
      // items: ["cucumber/test_runner/intro"],
    },
  ],
  cucumberMarkdownBar: [
    {
      type: "category",
      label: "Cucumber Markdown",
      items: [{ type: "autogenerated", dirName: "cucumber/cucumber_markdown" }],
    },
  ],
  libraryBar: ["libraries/intro"],
};

module.exports = sidebars;
