/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStarted: [
    {
      type: "category",
      label: "Getting started",
      link: { type: "doc", id: "getting-started/intro" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
  ],
  architecture: [
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
  ],
  reference: [
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
  ],
};

module.exports = sidebars;
