/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   "intro",
  //   {
  //     type: "category",
  //     label: "Tutorial",
  //     items: ["tutorial-basics/create-a-document"],
  //   },
  // ],
  introSidebar: [
    "intro",
    {
      type: "category",
      label: "Tutorial",
      items: ["tutorial-basics/create-a-document"],
    },
  ],
  playwrightBar: [
    "playwright/intro",
    {
      type: "category",
      label: "Page Components",
      items: ["playwright/page-components/intro"],
    },
  ],
  cucumberRunnerBar: [
    {
      type: "category",
      label: "Test Runner",
      items: [{ type: "autogenerated", dirName: "cucumber/test_runner" }],
      // items: ["cucumber/test_runner/intro"],
    },
  ],
  cucumberMarkdownBar: [
    {
      type: "category",
      label: "Cucumber Markdown",
      items: [{ type: "autogenerated", dirName: "cucumber/cucumber_markdown" }],
    },
  ],
  libraryBar: ["libraries/intro"],
};

module.exports = sidebars;
