/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   // link: {
    //   //   type: 'generated-index',
    //   // },
    //   collapsed: false,
    //   items: [
    //     'intro',
    //   ],
    // },
  ],
  // cucumber: [
  //   'cucumber/intro',
  // ],
  playwright: [
    'playwright/intro',
    {
      type: 'category',
      label: 'Page Components',
      // to: 'docs/playwright',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: 'playwright/',
      },
      items: [
        'playwright/page-components/page object model',
        'playwright/page-components/creating page components',
      ],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
