name: Integration Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_run:
      workflows: ['PR Workflow (windows)']
      types:
        - completed
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN}}
jobs:
  build:
    name: Build and Integration Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Build Runner
        run: pnpm build
      - name: Integration tests
        run: pnpm run integrate
