name: Run Unit Tests

on:
  pull_request:
    type: [opened, reopened, syncyronized, edited]

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - run: npm i -g pnpm
      - run: npm add -g turbo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - run: turbo test --filter=*integration*
